{% set version = "2.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-alphahull
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/alphahull_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/alphahull/alphahull_{{ version }}.tar.gz
  sha256: 82104b049b945b62b5b62f1520ff789a77638ab7e91650e50d6eb191373a8012

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-ggplot2
    - r-sgeostat
    - r-spatstat
    - r-splancs
    - r-tripack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-r.utils
    - r-ggplot2
    - r-sgeostat
    - r-spatstat
    - r-splancs
    - r-tripack

test:
  commands:
    - $R -e "library('alphahull')"           # [not win]
    - "\"%R%\" -e \"library('alphahull')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=alphahull
  license: LicenseRef-ACM
  summary: Computation of the alpha-shape and alpha-convex hull of a given sample of points in the plane. The concepts of alpha-shape and alpha-convex hull generalize the definition of the convex hull of a finite set of points. The programming is based on the duality between the Voronoi diagram and Delaunay triangulation.
    The package also includes a function that returns the Delaunay mesh of a given sample of points and its dual Voronoi diagram in one single object.
  license_family: OTHER
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - colineroyaux

# Package: alphahull
# Version: 2.2
# Date: 2019-06-19
# Title: Generalization of the Convex Hull of a Sample of Points in the Plane
# Author: Beatriz Pateiro-Lopez [aut, cre], Alberto Rodriguez-Casal, [aut].
# Maintainer: Beatriz Pateiro-Lopez <beatriz.pateiro@usc.es>
# Imports: ggplot2, tripack, R.utils, sgeostat, spatstat, splancs
# Description: Computation of the alpha-shape and alpha-convex hull of a given sample of points in the plane. The concepts of alpha-shape and alpha-convex hull generalize the definition of the convex hull of a finite set of points. The programming is based on the duality between the Voronoi diagram and Delaunay triangulation. The package also includes a function that returns the Delaunay mesh of a given sample of points and its dual Voronoi diagram in one single object.
# License: file LICENSE
# NeedsCompilation: yes
# License_restricts_use: yes
# Packaged: 2019-06-19 13:07:31 UTC; beatriz
# Repository: CRAN
# Date/Publication: 2019-06-21 17:30:03 UTC
